CREATE TABLE lifecycle_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    retention_days INTEGER CHECK (retention_days > 0),
    partition_strategy VARCHAR(10) NOT NULL CHECK (partition_strategy IN ('NONE', 'RANGE')),
    partition_interval_days INTEGER CHECK (partition_interval_days > 0),
    archive_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    archive_after_days INTEGER CHECK (archive_after_days > 0),
    delete_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    delete_after_days INTEGER CHECK (delete_after_days > 0),
    target_object_storage VARCHAR(500),
    execution_schedule VARCHAR(100),
    dry_run BOOLEAN NOT NULL DEFAULT TRUE CHECK (dry_run),
    CHECK (NOT archive_enabled OR (archive_after_days IS NOT NULL AND target_object_storage IS NOT NULL)),
    CHECK (NOT delete_enabled OR COALESCE(delete_after_days, retention_days) IS NOT NULL),
    CHECK (COALESCE(delete_after_days, retention_days) >= archive_after_days),
    CHECK ((partition_strategy = 'RANGE' AND partition_interval_days IS NOT NULL)
        OR (partition_strategy = 'NONE' AND partition_interval_days IS NULL))
);
CREATE TABLE policy_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL REFERENCES lifecycle_policy(id),
    database_id BIGINT NOT NULL REFERENCES database_connection(id),
    schema_name VARCHAR(63) NOT NULL,
    table_name VARCHAR(63) NOT NULL,
    UNIQUE (database_id, schema_name, table_name)
);
CREATE INDEX policy_assignment_policy_idx ON policy_assignment(policy_id);
